from . import stock_lot
from . import stock_picking
from . import purchase_order
from . import purchase_order_line
from . import res_partner
from . import fabric_return
from . import product_template
from . import mrp_production
from . import fabric_norm_variance_report
from . import fabric_production_insight_report
from . import fabric_shortage_forecast_report
from . import fabric_supplier_scorecard_report
from . import sale_order
from . import payment_provider
from . import payment_transaction
from . import stock_quant
from . import stock_lot_auto_name